export const CLIENT_UPLOAD_MAX_DIMENSION = 896;
export const CLIENT_UPLOAD_QUALITY = 0.56;

export const SERVER_STORAGE_MAX_DIMENSION = 1120;
export const SERVER_STORAGE_QUALITY = 62;

export const AI_ANALYSIS_MAX_DIMENSION = 896;
export const AI_ANALYSIS_QUALITY = 56;
